# Generated by Django 3.1.4 on 2020-12-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='messages',
        ),
    ]
